### ISSUE TITLE
敏感資訊洩漏

### ISSUE THREAD

**Issue by Vdragon** [klaymenr/rcfiles#1]
您好，我在此 [Google 搜尋結果](https://www.google.com.tw/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=VIVOTEK%20GPL) 找到您的下列這份文件：
<https://github.com/klaymenr/rcfiles/blob/master/.lftp/cwd_history>

因涉及到遠端伺服器的身份資訊提醒您進行必要的清理程序

**Comment by klaymenr** [comment]
收到! 很感謝您的提醒! 檔案已移除，謝謝!

**Comment by Vdragon** [comment]
@klaymenr 嚴格來說單純把檔案移除追蹤並不算是完全清乾淨（內容依然存在在過去的版本中），請參考：
<https://help.github.com/articles/remove-sensitive-data/>

不過我沒有使用這個 repo 所以也不在意有沒有處理好就是了，不關我的事:D
